### ISSUE TITLE
Chokes on IPv6?

### ISSUE THREAD

**Issue by larsskj** [imjoey/pyhaproxy#15]
Hi,

Just started evaluating you nice library - but unfortunately, it failed at the first attempt at parsing my quite simple configfile.

Apparently, it doesn't like my IPv6 bind:

`frontend http
    bind :::80 v4v6`

which should be a perfectly legal HAProxy command and works fine with my install.

Your code generates the following exception:

`Not specify host and port in `frontend` definition`

Regards,
Lars

**Comment by imjoey** [comment]
@larsskj It's indeed an issue. The `frontend bind` and `IPv6` are not supported yet. Currently, the `frontend` section only support the pattern of `frontend proxy_name host:port   # this's comment`. This issue would be fixed soon. Thanks for your contribution.

**Comment by larsskj** [comment]
Sounds nice - I'll look forward to that and stick to IPv4 for now.

Maybe it should be documented?

Regards,
Lars

**Comment by imjoey** [comment]
Yes, I will reevaluate the library by the latest haproxy configuration and document out the unsupported items currently.
