### ISSUE TITLE
`print` is missing brackets..

### ISSUE THREAD

**Issue by jennifer-bellizzi** [imjoey/pyhaproxy#17]
Due to prints missing brackets mainly in `render.py` and `pegnode.py` the module does not work with Python 3.

**Comment by kszczepek** [comment]
+1

**Comment by imjoey** [comment]
@jennifer-bellizzi @kszczepek I did not test the framework with PY3. I checked that the `print` clause makes nonsense. So I will remove the `print` clauses in these two files.
