### ISSUE TITLE
[BUG] Wrong parsing on pegnode

### ISSUE THREAD

**Issue by alisson276** [imjoey/pyhaproxy#25]
The pegnode parser treat all lines starting with server as a server_line.

My global section has the following:
```
global
        #log /dev/log    local0
        #log /dev/log    local1 notice
        log 127.0.0.1 local0 debug
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        server-state-base /etc/haproxy/serverstate
        server-state-file global
        user haproxy
        group haproxy
        daemon
        tune.ssl.default-dh-param 2048
```

The current parser understand the line `server-state-file global` as a server_line and render the config like this: 
```
<config_line: config log 127.0.0.1 local0 debug>
<config_line: config chroot /var/lib/haproxy>
<config_line: config stats socket /run/haproxy/admin.sock mode 660 level admin>
<config_line: config stats timeout 30s>
<config_line: config server-state-base /etc/haproxy/serverstate>
<server_line: -state-file global: >
<config_line: config user haproxy>
<group_line: group haproxy >
```

That behavior occur because the parser disregards the space (mandatory for a server section).

My fix was just edit 2 lines of pegnode.py and change from 6 to 7 and add a space:
```
                chunk0 = self._input[self._offset:self._offset + 7]
            if chunk0 == 'server ':
```

**Comment by imjoey** [comment]
Hi @alisson276 , thanks for your contribution. Could you please submit a pull request to fix this issue? Much appreciated. 😄

**Comment by alisson276** [comment]
Opened!

**Comment by alisson276** [comment]
Can you release a new patch version with the fix provided?

**Comment by imjoey** [comment]
@alisson276  Happy to announce that the latest version v0.3.7 is available on PYPI. Feel free to update. Thanks again for your contribution.

**Comment by alisson276** [comment]
Working. Thank you too!
