### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by eurodomenii** [imjoey/pyhaproxy#6]
**Modify existing value example**

```
# Find the specified ACL
acl_instance = the_fe_section.acl(the_acl_name)   # return config.Acl
acl_instance.value = "hdr(host) -i modified.example.com"

```
**Delete acl record example** 

```
# Get all the ACLs defined in the frontend section
acls = the_fe_section.acls()   # return list(config.Acl)
# Find the specified ACL
acl_instance = the_fe_section.acl(the_acl_name)   # return config.Acl
acls.remove(acl_instance)

```
**Append example failure**

`the_fe_section.acls().append(config.ACL(acl_name, acl_value))  # append the ACL into the frontend section
` fails with  _NameError: name 'config' is not defined_

Finally , a small observation 

```
for usebe in usebackends:
    # Get the using backend name, operator, condition
    print usebe.backend_name, usebe.operator, backend_condition

```
Should be _usebe.backend_condition_

**Btw, nice piece of software!**

**Comment by imjoey** [comment]
@eurodomenii Thanks for your issue, I fix the bugs and add the examples as you mentioned. It's recommended that you could submit a PR to add your codes. ^_^

**Comment by eurodomenii** [comment]
Thanks for the fix @imjoey . My contribution is limited to several examples... In the future, if I have something substantial, I'll commit.
